import turtle as t

t.bgcolor("white")
t.color("black", "red")
t.speed(5)
t.pensize(5)
t.begin_fill()
t.circle(100)
t.end_fill()
t.penup()
t.goto(0, 0)
t.left(90)
t.forward(100)
t.right(165)
t.pendown()
for i in range(124):
    t.forward(i/7)  
    t.right(10) 
t.color("black","black")
t.penup()
t.goto(0, 0)
t.setheading(90)
t.forward(95)
t.right(90)
t.pendown()
t.begin_fill()
t.circle(5) 
t.end_fill()
t.hideturtle()
t.done()


